import { pgTable,uuid,text,bigint,boolean,timestamp,jsonb,integer,unique,foreignKey,primaryKey,index,check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import type { EncryptedSecret } from '@humanize/security';

const id=()=>uuid('id').primaryKey().defaultRandom();
const created=()=>timestamp('created_at',{withTimezone:true}).notNull().defaultNow();
export const users=pgTable('users',{id:id(),githubUserId:bigint('github_user_id',{mode:'number'}).notNull().unique(),createdAt:created()});
export const organizations=pgTable('organizations',{id:id(),githubAccountId:bigint('github_account_id',{mode:'number'}).notNull().unique(),enabled:boolean('enabled').notNull().default(true),createdAt:created()});
export const organizationMembers=pgTable('organization_members',{organizationId:uuid('organization_id').notNull().references(()=>organizations.id,{onDelete:'cascade'}),userId:uuid('user_id').notNull().references(()=>users.id,{onDelete:'cascade'})},t=>[primaryKey({columns:[t.organizationId,t.userId]})]);
export const installations=pgTable('github_installations',{id:bigint('id',{mode:'number'}).primaryKey(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id,{onDelete:'cascade'}),suspended:boolean('suspended').notNull().default(false),deleted:boolean('deleted').notNull().default(false),createdAt:created()},t=>[unique().on(t.organizationId,t.id)]);
export const repositories=pgTable('repositories',{id:id(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id,{onDelete:'cascade'}),installationId:bigint('installation_id',{mode:'number'}).notNull(),githubRepositoryId:bigint('github_repository_id',{mode:'number'}).notNull().unique(),owner:text('owner').notNull(),name:text('name').notNull(),defaultBranch:text('default_branch').notNull().default('main'),enabled:boolean('enabled').notNull().default(false),retentionMode:text('retention_mode').notNull().default('ephemeral'),policyVersion:integer('policy_version').notNull().default(1),createdAt:created()},t=>[unique().on(t.organizationId,t.id),foreignKey({columns:[t.organizationId,t.installationId],foreignColumns:[installations.organizationId,installations.id]}),check('repository_retention',sql`${t.retentionMode} in ('ephemeral','indexed')`)]);
const scope=()=>({organizationId:uuid('organization_id').notNull(),repositoryId:uuid('repository_id').notNull()});
export const repositoryConfigs=pgTable('repository_configs',{...scope(),version:integer('version').notNull(),configSha:text('config_sha').notNull(),configHash:text('config_hash').notNull(),configuration:jsonb('configuration').notNull(),createdAt:created()},t=>[primaryKey({columns:[t.organizationId,t.repositoryId,t.version]}),foreignKey({columns:[t.organizationId,t.repositoryId],foreignColumns:[repositories.organizationId,repositories.id],name:'config_repository_scope'})]);
export const providerCredentials=pgTable('provider_credentials',{id:id(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id,{onDelete:'cascade'}),provider:text('provider').notNull(),encrypted:jsonb('encrypted').$type<EncryptedSecret>().notNull(),revokedAt:timestamp('revoked_at',{withTimezone:true}),createdAt:created()},t=>[unique().on(t.organizationId,t.id)]);
export const modelProfiles=pgTable('model_profiles',{id:id(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id,{onDelete:'cascade'}),credentialId:uuid('credential_id'),provider:text('provider').notNull(),model:text('model').notNull(),capabilities:jsonb('capabilities'),createdAt:created()},t=>[unique().on(t.organizationId,t.id),foreignKey({columns:[t.organizationId,t.credentialId],foreignColumns:[providerCredentials.organizationId,providerCredentials.id]})]);
export const webhookDeliveries=pgTable('webhook_deliveries',{deliveryId:text('delivery_id').primaryKey(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id,{onDelete:'cascade'}),eventType:text('event_type').notNull(),action:text('action').notNull(),metadata:jsonb('metadata'),createdAt:created()});
export const pullRequests=pgTable('pull_requests',{...scope(),number:integer('number').notNull(),headSha:text('head_sha').notNull(),baseSha:text('base_sha').notNull(),state:text('state').notNull(),draft:boolean('draft').notNull(),generation:integer('generation').notNull().default(1),createdAt:created(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()},t=>[primaryKey({columns:[t.organizationId,t.repositoryId,t.number]}),foreignKey({columns:[t.organizationId,t.repositoryId],foreignColumns:[repositories.organizationId,repositories.id]})]);
export const reviewRuns=pgTable('review_runs',{id:id(),...scope(),pullNumber:integer('pull_number').notNull(),headSha:text('head_sha').notNull(),configHash:text('config_hash').notNull(),generation:integer('generation').notNull(),state:text('state').notNull(),attempt:integer('attempt').notNull().default(0),retentionMode:text('retention_mode').notNull(),snapshot:jsonb('snapshot').notNull(),errorClass:text('error_class'),createdAt:created(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()},t=>[unique().on(t.organizationId,t.repositoryId,t.id),unique().on(t.organizationId,t.repositoryId,t.pullNumber,t.headSha,t.configHash,t.generation),foreignKey({columns:[t.organizationId,t.repositoryId],foreignColumns:[repositories.organizationId,repositories.id]}),index('run_state_idx').on(t.state,t.updatedAt)]);
export const findings=pgTable('findings',{id:id(),...scope(),runId:uuid('run_id').notNull(),fingerprint:text('fingerprint').notNull(),category:text('category').notNull(),severity:text('severity').notNull(),filePath:text('file_path').notNull(),startLine:integer('start_line').notNull(),endLine:integer('end_line').notNull(),retentionMode:text('retention_mode').notNull(),explanation:text('explanation'),replacement:text('replacement'),createdAt:created()},t=>[unique().on(t.organizationId,t.repositoryId,t.id),unique().on(t.runId,t.fingerprint),foreignKey({columns:[t.organizationId,t.repositoryId,t.runId],foreignColumns:[reviewRuns.organizationId,reviewRuns.repositoryId,reviewRuns.id]}),check('finding_privacy',sql`${t.retentionMode} = 'indexed' or (${t.retentionMode} = 'ephemeral' and ${t.explanation} is null and ${t.replacement} is null)`)]);
export const findingEvidence=pgTable('finding_evidence',{id:id(),...scope(),findingId:uuid('finding_id').notNull(),evidenceId:text('evidence_id').notNull(),contentHash:text('content_hash').notNull(),retentionMode:text('retention_mode').notNull(),quote:text('quote')},t=>[foreignKey({columns:[t.organizationId,t.repositoryId,t.findingId],foreignColumns:[findings.organizationId,findings.repositoryId,findings.id]}),check('evidence_privacy',sql`${t.retentionMode} = 'indexed' or (${t.retentionMode} = 'ephemeral' and ${t.quote} is null)`)]);
export const publicationAttempts=pgTable('publication_attempts',{id:id(),...scope(),runId:uuid('run_id').notNull(),headSha:text('head_sha').notNull(),digest:text('digest').notNull(),marker:text('marker').notNull(),state:text('state').notNull().default('PREPARED'),remoteReviewId:bigint('remote_review_id',{mode:'number'}),remoteCheckId:bigint('remote_check_id',{mode:'number'}),createdAt:created(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()},t=>[unique().on(t.runId),foreignKey({columns:[t.organizationId,t.repositoryId,t.runId],foreignColumns:[reviewRuns.organizationId,reviewRuns.repositoryId,reviewRuns.id]})]);
export const publishedComments=pgTable('published_comments',{id:id(),...scope(),runId:uuid('run_id').notNull(),fingerprint:text('fingerprint').notNull(),remoteId:bigint('remote_id',{mode:'number'}).notNull(),createdAt:created()},t=>[unique().on(t.organizationId,t.repositoryId,t.remoteId),foreignKey({columns:[t.organizationId,t.repositoryId,t.runId],foreignColumns:[reviewRuns.organizationId,reviewRuns.repositoryId,reviewRuns.id]})]);
export const runnerEnrollments=pgTable('runner_enrollments',{id:id(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id,{onDelete:'cascade'}),tokenHash:text('token_hash').notNull().unique(),repositoryIds:uuid('repository_ids').array().notNull(),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull(),consumedAt:timestamp('consumed_at',{withTimezone:true}),createdAt:created()});
export const runners=pgTable('runners',{id:id(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id,{onDelete:'cascade'}),credentialHash:text('credential_hash').notNull().unique(),repositoryIds:uuid('repository_ids').array().notNull(),capabilities:jsonb('capabilities').notNull(),lastHeartbeat:timestamp('last_heartbeat',{withTimezone:true}).notNull().defaultNow(),revokedAt:timestamp('revoked_at',{withTimezone:true}),createdAt:created()},t=>[unique().on(t.organizationId,t.id)]);
export const runnerLeases=pgTable('runner_leases',{id:id(),...scope(),runId:uuid('run_id').notNull().unique(),runnerId:uuid('runner_id'),state:text('state').notNull().default('QUEUED'),fence:integer('fence').notNull().default(0),attempts:integer('attempts').notNull().default(0),expiresAt:timestamp('expires_at',{withTimezone:true}),resultHash:text('result_hash'),createdAt:created()},t=>[foreignKey({columns:[t.organizationId,t.repositoryId,t.runId],foreignColumns:[reviewRuns.organizationId,reviewRuns.repositoryId,reviewRuns.id]}),foreignKey({columns:[t.organizationId,t.runnerId],foreignColumns:[runners.organizationId,runners.id]}),index('lease_claim_idx').on(t.organizationId,t.state,t.expiresAt)]);
/**
 * The validated payload awaiting publication (ADR-038). Written when a runner result is
 * accepted and deleted as soon as publication completes or is abandoned, so ephemeral mode
 * keeps a lifetime guarantee rather than an absolute one. A sweep removes anything a crash
 * left behind.
 */
export const publicationPayloads=pgTable('publication_payloads',{...scope(),runId:uuid('run_id').primaryKey(),retentionMode:text('retention_mode').notNull(),payload:jsonb('payload').notNull(),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull(),createdAt:created()},t=>[foreignKey({columns:[t.organizationId,t.repositoryId,t.runId],foreignColumns:[reviewRuns.organizationId,reviewRuns.repositoryId,reviewRuns.id]}),index('publication_expiry_idx').on(t.expiresAt)]);
/**
 * Administrator-owned settings: provider and model roles, retention and execution mode, the
 * inline comment cap and the permitted category set. Repository content can never reach these
 * fields, which is why they live apart from repository_configs (ADR-027).
 */
export const organizationPolicies=pgTable('organization_policies',{organizationId:uuid('organization_id').primaryKey().references(()=>organizations.id,{onDelete:'cascade'}),version:integer('version').notNull().default(1),policy:jsonb('policy').notNull(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()});
/** Explicit project knowledge an administrator wrote down, scoped to paths (spec 25.1). */
export const explicitLearnings=pgTable('explicit_learnings',{id:id(),...scope(),scopeGlobs:text('scope_globs').array().notNull(),rule:text('rule').notNull(),enabled:boolean('enabled').notNull().default(true),createdBy:text('created_by').notNull(),createdAt:created(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()},t=>[foreignKey({columns:[t.organizationId,t.repositoryId],foreignColumns:[repositories.organizationId,repositories.id]}),index('learning_scope_idx').on(t.organizationId,t.repositoryId,t.enabled)]);
/**
 * What happened to a published finding. Provenance is recorded because a single dismissal
 * must never become a permanent rule (spec 25.2); turning feedback into a rule is a separate,
 * explicit act by an administrator.
 */
export const feedback=pgTable('feedback',{id:id(),...scope(),runId:uuid('run_id').notNull(),fingerprint:text('fingerprint').notNull(),outcome:text('outcome').notNull(),source:text('source').notNull(),actor:text('actor'),createdAt:created()},t=>[foreignKey({columns:[t.organizationId,t.repositoryId,t.runId],foreignColumns:[reviewRuns.organizationId,reviewRuns.repositoryId,reviewRuns.id]}),unique().on(t.runId,t.fingerprint,t.outcome,t.source),check('feedback_outcome',sql`${t.outcome} in ('accepted_suggestion','dismissed','manual_fix','false_positive','intentional_wording','resolved_by_new_commit','outdated')`),check('feedback_source',sql`${t.source} in ('explicit','inferred')`)]);
