"""Update one task and regenerate the persistent implementation handoff."""
from pathlib import Path
from datetime import datetime, timezone
import argparse
import json
import re

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('task')
parser.add_argument('status', choices=['planned', 'in_progress', 'blocked', 'complete'])
parser.add_argument('--evidence', required=True)
parser.add_argument('--next', required=True)
args = parser.parse_args()
manifest_path = root / 'docs/implementation/manifest.json'
manifest = json.loads(manifest_path.read_text())
tasks = [task for stage in manifest['stages'] for task in stage['tasks']]
task = next(task for task in tasks if task['id'] == args.task)
now = datetime.now(timezone.utc).isoformat()
task.update(status=args.status, evidence=args.evidence, nextAction=args.next, updatedAt=now)
manifest_path.write_text(json.dumps(manifest, indent=2) + '\n')
path = root / f'docs/implementation/tasks/{args.task}.md'
body = re.sub(r'^Status: .*$', 'Status: ' + args.status, path.read_text(), flags=re.M)
body = body.split('## Completion evidence')[0] + f'''## Completion evidence

- Last updated: {now}.
- Implementation revision: current working tree; no commit claimed.
- Evidence: {args.evidence}
- Next action / remaining acceptance: {args.next}
'''
path.write_text(body)
with (root / 'docs/implementation/evidence/progress.jsonl').open('a') as log:
    log.write(json.dumps({'at': now, 'task': args.task, 'status': args.status, 'evidence': args.evidence, 'next': args.next}) + '\n')
lines = ['# Implementation status and handoff\n',
         f'Last task update: {now}. Generated by `scripts/update_progress.py`; task records and manifest are authoritative.\n',
         '**Phase 1 is not complete or production-ready.** Code existence does not establish live compatibility, human quality or operational readiness.\n',
         'Read [HANDOFF.md](HANDOFF.md) first for current failures, commands, environment and next steps. Then read the assigned [task](README.md).\n',
         '| Stage | Complete | In progress | Blocked | Planned |', '|---|---:|---:|---:|---:|']
for stage in manifest['stages']:
    counts = [sum(t['status'] == status for t in stage['tasks']) for status in ['complete', 'in_progress', 'blocked', 'planned']]
    lines.append(f'| {stage["id"]} — {stage["title"]} | ' + ' | '.join(map(str, counts)) + ' |')
lines += ['\n## Tasks with implementation or validation activity\n', '| Task | State | Evidence | Remaining / next action |', '|---|---|---|---|']
for t in tasks:
    if t['status'] == 'planned':
        continue
    clean = lambda text: text.replace('|', '/').replace('\n', ' ')
    lines.append(f'| [{t["id"]}](tasks/{t["id"]}.md) | {t["status"]} | {clean(t.get("evidence", ""))} | {clean(t.get("nextAction", ""))} |')
lines += ['\nUntouched tasks remain explicitly **planned** in the [manifest](manifest.json) and linked task records. All 104 upstream tasks remain covered by the [crosswalk](crosswalk.md).\n']
(root / 'docs/implementation/STATUS.md').write_text('\n'.join(lines))
